services:
  - type: worker
    name: telegram-ytdlp-bot
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
